# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Nikhil J Joshi
email: n.j.joshi@gmail.com
description: A Deep Learning Meanderer
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: nikhil_j_joshi
#github_username: nikhiljjoshi
linkedin_username: nikhil-j-joshi-54697318
#facebook_username: nikhiljajoshi
#google_plus_username: +NikhilJJoshi
#stackoverflow_username: users/899216/nikhil-j-joshi

# Build settings
markdown: kramdown
